Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -2,10 +2,10 @@
 
 DOTFILES="$(pwd)"
 COLOR_GRAY="\033[1;38;5;243m"
+COLOR_PURPLE="\033[1;35m"
+COLOR_RED="\033[1;31m"
 COLOR_BLUE="\033[1;34m"
 COLOR_GREEN="\033[1;32m"
-COLOR_RED="\033[1;31m"
-COLOR_PURPLE="\033[1;35m"
 COLOR_YELLOW="\033[1;33m"
 COLOR_NONE="\033[0m"
 
@@ -14,43 +14,53 @@ title() {
   echo -e "${COLOR_GRAY}==============================${COLOR_NONE}\n"
 }
 
+err() {
+  echo -e "${COLOR_RED}ERROR: ${COLOR_NONE}$1"
+}
+
+warn() {
+    echo -e "${COLOR_YELLOW}WARNING: ${COLOR_NONE}$1"
+}
+
 info() {
-  echo -e "${COLOR_BLUE}Info: ${COLOR_NONE}$1"
+  echo -e "${COLOR_BLUE}INFO: ${COLOR_NONE}$1"
 }
 
 success() {
   echo -e "${COLOR_GREEN}$1${COLOR_NONE}"
 }
 
-get_linkables() {
-    find -H "$DOTFILES" -maxdepth 3 -name '*.symlink'
-}
+setup_dotfiles() {
+  title "Downloading dotfiles"
 
-backup() {
-  BACKUP_DIR=$HOME/dotfiles-backup
+  echo -e
+  info "downloading dotfiles"
+  DOTFILES=(
+    .aqua.yaml
+    .editorconfig
+    .gitconfig
+    .tool-versions
+    .zprofile
+    .zshrc
+  )
 
-  echo "Creating backup directory at $BACKUP_DIR"
-  mkdir -p "$BACKUP_DIR"
-
-  for file in $(get_linkables); do
-    filename=".$(basename "$file" '.symlink')"
-    target="$HOME/$filename"
-    if [ -f "$target" ]; then
-      echo "backing up $filename"
-      cp "$target" "$BACKUP_DIR"
+  for dotfile in "${DOTFILES[@]}"; do
+    if [ -e "$HOME/$dotfile" ]; then
+      info "~${dotfile#$HOME} already exists... Skipping."
     else
-      warning "$filename does not exist at this location or is a symlink"
+      info "Downloading $HOME/$dotfile"
+      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/grimoh/dorfiles/HEAD/$dotfile)"
     fi
   done
 
-  for filename in "$HOME/.config/nvim" "$HOME/.vim" "$HOME/.vimrc"; do
-    if [ ! -L "$filename" ]; then
-      echo "backing up $filename"
-      cp -rf "$filename" "$BACKUP_DIR"
-    else
-      warning "$filename does not exist at this location or is a symlink"
-    fi
-  done
+  echo -e
+  info "installing .config"
+  if [ -d "$HOME/.config" ]; then
+    info "$HOME/.config already exists... Skipping."
+  else
+    info "Downloading $HOME/.config"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/grimoh/dorfiles/HEAD/.config)"
+  fi
 }
 
 setup_homebrew() {
@@ -59,7 +69,7 @@ setup_homebrew() {
   # install if Homebrew is not installed
   if test ! "$( command -v brew )"; then
     info "Homebrew not installed. Installing."
-    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | bash --login
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   fi
 
   # for Linux
@@ -96,171 +106,156 @@ setup_fish(){
   fish -C 'fisher install "${FISHER_PACKAGE[@]}" || :'
 }
 
-setup_symlinks() {
-  title "Creating symlinks"
-
-  for file in $(get_linkables) ; do
-    target="$HOME/.$(basename "$file" '.symlink')"
-    if [ -e "$target" ]; then
-      info "~${target#$HOME} already exists... Skipping."
-    else
-      info "Creating symlink for $file"
-      ln -s "$file" "$target"
-    fi
-  done
-
-  echo -e
-  info "installing to ~/.config"
-  if [ ! -d "$HOME/.config" ]; then
-    info "Creating ~/.config"
-    mkdir -p "$HOME/.config"
-  fi
-
-  config_files=$(find "$DOTFILES/config" -maxdepth 1 2>/dev/null)
-  for config in $config_files; do
-    target="$HOME/.config/$(basename "$config")"
-    if [ -e "$target" ]; then
-      info "~${target#$HOME} already exists... Skipping."
-    else
-      info "Creating symlink for $config"
-      ln -s "$config" "$target"
-    fi
-  done
-}
-
 setup_macos(){
   title "Configuring macOS"
   if [[ "$(uname)" == "Darwin" ]]; then
 
-  # install command line tools for xcode
-  if [ ! -d /Library/Developer/CommandLineTools ]; then
-    info "xcode not installed. Installing."
-	  xcode-select --install
-  fi
+    # make working space dir
+    mkdir -p $HOME/Documents/workspace
 
-  echo "Finder: show all filename extensions"
-  defaults write NSGlobalDomain AppleShowAllExtensions -bool true
+    # install command line tools for xcode
+    if [ ! -d /Library/Developer/CommandLineTools ]; then
+      info "xcode not installed. Installing."
+	    xcode-select --install
+    fi
 
-  echo "show hidden files by default"
-  defaults write com.apple.Finder AppleShowAllFiles -bool false
+    echo "Finder: show all filename extensions"
+    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
 
-  echo "only use UTF-8 in Terminal.app"
-  defaults write com.apple.terminal StringEncodings -array 4
+    echo "show hidden files by default"
+    defaults write com.apple.Finder AppleShowAllFiles -bool false
 
-  echo "expand save dialog by default"
-  defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
+    echo "only use UTF-8 in Terminal.app"
+    defaults write com.apple.terminal StringEncodings -array 4
 
-  echo "show the ~/Library folder in Finder"
-  chflags nohidden ~/Library
+    echo "expand save dialog by default"
+    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
 
-  echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
-  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
+    echo "show the ~/Library folder in Finder"
+    chflags nohidden ~/Library
 
-  echo "Enable subpixel font rendering on non-Apple LCDs"
-  defaults write NSGlobalDomain AppleFontSmoothing -int 2
+    echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
+    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
 
-  echo "Use current directory as default search scope in Finder"
-  defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
+    echo "Enable subpixel font rendering on non-Apple LCDs"
+    defaults write NSGlobalDomain AppleFontSmoothing -int 2
 
-  echo "Show Path bar in Finder"
-  defaults write com.apple.finder ShowPathbar -bool true
+    echo "Use current directory as default search scope in Finder"
+    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
 
-  echo "Show Status bar in Finder"
-  defaults write com.apple.finder ShowStatusBar -bool true
+    echo "Show Path bar in Finder"
+    defaults write com.apple.finder ShowPathbar -bool true
 
-  echo "Disable press-and-hold for keys in favor of key repeat"
-  defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
+    echo "Show Status bar in Finder"
+    defaults write com.apple.finder ShowStatusBar -bool true
 
-  echo "Set a blazingly fast keyboard repeat rate"
-  defaults write NSGlobalDomain KeyRepeat -int 1
+    echo "Disable press-and-hold for keys in favor of key repeat"
+    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
 
-  echo "Set a shorter Delay until key repeat"
-  defaults write NSGlobalDomain InitialKeyRepeat -int 15
+    echo "Set a blazingly fast keyboard repeat rate"
+    defaults write NSGlobalDomain KeyRepeat -int 1
 
-  echo "Enable tap to click (Trackpad)"
-  defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
+    echo "Set a shorter Delay until key repeat"
+    defaults write NSGlobalDomain InitialKeyRepeat -int 15
 
-  echo "Enable Safari’s debug menu"
-  defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
+    echo "Enable tap to click (Trackpad)"
+    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
 
-  echo "Kill affected applications"
-  for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
+    echo "Enable Safari’s debug menu"
+    defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
+
+    echo "Kill affected applications"
+    for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
   else
-    warning "macOS not detected. Skipping."
+    warn "macOS not detected. Skipping."
   fi
 }
 
-cat <<EOS
-#####################################
-# pre setup
-#####################################
-EOS
+setup_asdfvm(){
+  title "Setting up asdf-vm"
 
-echo "# make workspace and package dir"
-mkdir -p $HOME/Documents/workspace
-mkdir -p $HOME/.packages/go
-mkdir -p $HOME/.packages/npm
+  # add asdf plugins
+  asdf plugin add 1password-cli
+  asdf plugin add nodejs
+  asdf plugin add python
+  asdf plugin add rubbish https://github.com/grimoh/asdf-rubbish.git
+  asdf plugin add ruby
 
-echo "# cd root"
-cd $HOME
+  # install asdf plugins
+  asdf install
+}
 
-cat <<EOS
-#####################################
-# asdf
-#####################################
-EOS
+setup_neovim(){
+  title "Setting up neovim"
 
-echo "# add asdf plugins"
-asdf plugin add 1password-cli
-asdf plugin add nodejs
-asdf plugin add python
-asdf plugin add rubbish https://github.com/grimoh/asdf-rubbish.git
-asdf plugin add ruby
+  # install packer(neovim package management plugin) if not installed
+  if ! ( ! -d ~/.local/share/nvim/site/pack/packer/opt/packer.nvim ); then
+    info "Packer not installed. Installing."
+    git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/opt/packer.nvim
+  fi
+}
 
-echo "# install asdf plugins"
-asdf install
+setup_packages(){
+  title "Install packages"
 
-cat <<EOS
-#####################################
-# neovim
-#####################################
-EOS
+  # make package
+  mkdir -p $HOME/.packages/go $HOME/.packages/npm
 
-echo "# install packer(neovim package management plugin) if not installed"
-if ! ( ! -d ~/.local/share/nvim/site/pack/packer/opt/packer.nvim ); then
-  git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/opt/packer.nvim
-fi
+  # install gem packages
+  gem install neovim
 
-echo "# run neovim"
-nvim
+  # install python packages
+  python3 -m pip install pynvim
 
-cat <<EOS
-#####################################
-# packages
-#####################################
-EOS
+  # install npm packages
+  npm install --global neovim
+  npm install --global dockerfile-language-server-nodejs
+  npm install --global eclint
+  npm install --global quick-lint-js
+  npm install --global typescript-language-server
+  npm install --global typescript
+  npm install --global yaml-language-server
 
-echo "# install gem packages"
-gem install neovim
+  # install go packages
+  go install golang.org/x/tools/gopls@latest
+}
 
-echo "# install python packages"
-python3 -m pip install pynvim
-
-echo "# install npm packages"
-npm install --global neovim
-npm install --global dockerfile-language-server-nodejs
-npm install --global eclint
-npm install --global quick-lint-js
-npm install --global typescript-language-server
-npm install --global typescript
-npm install --global yaml-language-server
-
-echo "# install go packages"
-go install golang.org/x/tools/gopls@latest
-
-cd
-rm -rf .setup
-echo "# setup completed"
+case "$1" in
+  link)
+    setup_symlinks
+    ;;
+  homebrew)
+    setup_homebrew
+    ;;
+  fish)
+    setup_fish
+    ;;
+  macos)
+    setup_macos
+    ;;
+  asdfvm)
+    setup_asdfvm
+    ;;
+  neovim)
+    setup_neovim
+    ;;
+  pkgs)
+    setup_packages
+    ;;
+  all)
+    setup_symlinks
+    setup_homebrew
+    setup_fish
+    setup_macos
+    setup_asdfvm
+    setup_neovim
+    setup_packages
+    ;;
+  *)
+    echo -e $"\nUsage: $(basename "$0") {link|homebrew|fish|macos|asdfvm|nepvim|pkgs|all}\n"
+    exit 1
+    ;;
+esac
 
 echo -e
 success "Done."
